### PR TITLE
Add colors to the object doc

### PR DESCRIPTION
**Pull request by t-wissmann**
This adds colors to the attribute names and types and child names in the
object doc. Also, this inserts a colon between the attribute
specification and the doc string.

Moreover, 'code' is an html tag not a class, so main.css had to be
adjusted.

### CODE REVIEW

**Comment by blarz** [comment]
Sometimes there is a whitespace between the colon and the attribute, is this intended?

> active : configures the decoration of the focused client.

but 
> string reset: writing this resets all attributes to a default value

for example

**Comment by t-wissmann** [comment]
> Sometimes there is a whitespace between the colon and the attribute, is this intended?
> 
> > active : configures the decoration of the focused client.
> 
> but
> 
> > string reset: writing this resets all attributes to a default value
> 
> for example

`active` is a child entry whereas `reset` is an attribute. The whitespace issue for child entries existed before, but I can fix it along with this PR.

**Comment by t-wissmann** [comment]
When trying to make the colon usage for child entries consistent, I had to adjust further parts, but I hope the output is OK now.

**Comment by blarz** [comment]
> When trying to make the colon usage for child entries consistent, I had to adjust further parts, but I hope the output is OK now.

Looks very good now, thank you for fixing this!

**Review by blarz — APPROVED** [review]

**Pull request merged**
