### PR TITLE
Add a default unminimize shortcut

### PR DESCRIPTION
**Pull request by apm256**
Solve #1133 by offering an un-minimize shortcut in the default autostart.

### CODE REVIEW

**Review by t-wissmann — APPROVED** [review]
Works well and the command looks nice, thanks :-)

**Comment by M1ndo** [comment]
@apm256 is there a way to un-minimize the latest un-minimized client at a time instead of all the minimized clients.

**Comment by apm256** [comment]
I'm afraid it is not possible with a mere call to `herbstclient`.

Nevertheless, This feature should be scriptable (for instance, by using one fifo queue per tag, and react to a custom hook by adding the focused window to the queue, then minimizing it).

**Comment by apm256** [comment]
@M1ndo : you can try the following scripts:

minimize.sh

```
#!/bin/bash

herbstclient silent new_attr int my_minimized_counter 1

herbstclient chain \
  . silent chain \
    : substitute C my_minimized_counter new_attr int clients.focus.my_minimized_age C \
    : set_attr my_minimized_counter $(($(herbstclient substitute C my_minimized_counter echo C)+1)) \
  .  set_attr clients.focus.minimized true \
```

(don't forget to `chmod +x` the file)


and, in `autostart`:

```
Mod=Mod4

# minimize current window
herbstclient keybind $Mod-Shift-m spawn ~/.config/herbstluftwm/minimize.sh

# unminimize last window of a tag
herbstclient keybind $Mod-Ctrl-m mktemp string MINCLIENT mktemp int LASTIDATT chain \
  . set_attr LASTIDATT 0 \
  . foreach CLIENT clients. and \
    , sprintf MINATT "%c.minimized" CLIENT \
        compare MINATT "=" "true" \
    , sprintf TAGATT "%c.tag" CLIENT substitute FOCUS "tags.focus.name" \
        compare TAGATT "=" FOCUS \
    , sprintf CURRENTIDATT "%c.my_minimized_age" CLIENT and \
      : substitute LASTID LASTIDATT \
          compare CURRENTIDATT 'gt' LASTID \
      : substitute CURRENTID CURRENTIDATT \
          set_attr LASTIDATT CURRENTID \
    , set_attr MINCLIENT CLIENT \
  . and \
    , compare MINCLIENT "!=" "" \
    , substitute CLIENT MINCLIENT chain \
      : sprintf MINATT "%c.minimized" CLIENT \
          set_attr MINATT false \
      : sprintf CURRENTIDATT "%c.my_minimized_age" CLIENT \
          remove_attr CURRENTIDATT \
```

We can *almost* use exclusively herbstluftwm to script such a behavior except, that, in my knowledge (cc @t-wissmann ), it is not possible to increment a counter, so we have to use bash in this way:

```
set_attr my_minimized_counter $(($(herbstclient substitute C my_minimized_counter echo C)+1))
```

**Comment by M1ndo** [comment]
@apm256 Sorry for the delay , i have just tested your script And i gotta say it's fantastic it works like a charm .
Thanks a lot for bringing out a solution for this (cc @t-wissmann you should definitely add this trick to the docs).

**Pull request merged**
