### PR TITLE
Add tests for rules

### PR DESCRIPTION
**Pull request by dnnr**

### CODE REVIEW

**Comment by dnnr** [comment]
The build failed due to some postgres mirror being down. Someone with the right privileges needs to retrigger it.

**Comment by t-wissmann** [comment]
I can't find any proper way of triggering a rebuild. But one workaround is to close this PR and open it again.

**Comment by dnnr** [comment]
Whatever works I guess :100:
Fwiw, I see this button in my Travis:

**Comment by t-wissmann** [comment]
I am quite sure that I did not have this button.

**Pull request merged**
