### PR TITLE
Changed XFetchName to XGetWMName, fixing issue #64

### PR DESCRIPTION
**Pull request by prohunterdogkeeper**
Changed XFetchName to XGetWMName as described in issue #64, first time contributing to any project and first time writing and not just reading C/C++ so please go ahead and reject / tell me if I did something wrong.

### CODE REVIEW

**Comment by ypnos** [comment]
Looks pretty good to me. In two lines the indention seems to be off by one character.
Nice job!

**Comment by prohunterdogkeeper** [comment]
Yeah, line 873 and 874?
I have no idea where that came from, it's not there in my fork? I haven't changed anything since the pull request.

**Comment by ypnos** [comment]
The problem is that sometimes you have tabs in there, while the rest of the file indents with spaces.

Because Thorsten likes clean commits, I suggest you replace your tabs with spaces, then do a `git commit -a -v --amend` and then push fast-forward (`git push -f`), something that normally should **not** be done. Then it will stay one commit. No need to redo the pull request.

**Comment by prohunterdogkeeper** [comment]
Alright, fixed. Thanks for the help.

**Comment by The-Compiler** [comment]
> and then push fast-forward (`git push -f`)

You mean force-push - fast-forward is when you're pulling and there is no merge because it's the same base :wink:

**Pull request merged**
