### PR TITLE
Make title alignment configurable

### PR DESCRIPTION
**Pull request by t-wissmann**
This adds a new attribute title_align that configures the horizontal
alignment of the window title within the title bar, respectively tab.

This was requested in #1097.

### CODE REVIEW

**Comment by blarz** [comment]
Left aligned text has some padding, right aligned doesn't and it looks a bit a bit odd IMHO.

Should the same padding be applied to the right, too?

**Comment by t-wissmann** [comment]
> Left aligned text has some padding, right aligned doesn't and it looks a bit a bit odd IMHO.
> 
> Should the same padding be applied to the right, too?

Well spotted, Thanks! I've applied the pad also to the 'width', but of course I have to apply it twice. I've fixed it :-)

**Comment by blarz** [comment]
> > Left aligned text has some padding, right aligned doesn't and it looks a bit a bit odd IMHO.
> > Should the same padding be applied to the right, too?
> 
> Well spotted, Thanks! I've applied the pad also to the 'width', but of course I have to apply it twice. I've fixed it :-)

Great, thank you, right align looks good now :)

**Review by blarz — APPROVED** [review]
Very cool, thank you!

**Comment by t-wissmann** [comment]
There is an issue with mergify, I am taking a look at it.

**Pull request merged**
