### PR TITLE
Extract separate CI job for linting/static analysis

### PR DESCRIPTION
**Pull request by dnnr**

### CODE REVIEW

**Comment by dnnr** [comment]
This ended up a bit more verbose in `.travis.yml` than I'd like it to be. I'm open to suggestions.

In any case, I think it's still an acceptable fix for #399.

**Comment by t-wissmann** [comment]
Great, thanks a lot! This really makes my life easier when preparing new PRs!

I don't know how to reduce the redundancy from the .travis.yml. I also didn't know that IWYU requires compiled sources. In gitlab there is this notion of different stages that can pass intermediate results to each other. But I fear in travis we have to re-compile it, right?

**Comment by dnnr** [comment]
> I also didn't know that IWYU requires compiled sources.

Oh, it doesn't. It just needs the generated build directory, hence the new `--compile` flag which makes the actual compilation step optional.

The significant waste/overhead (as in: duplicate operations) introduced by this PR is happening *outside* of `ci-build.py`: Booting the VM and doing the Docker stuff. But all things considered, I find this acceptable.

**Comment by dnnr** [comment]
...and no, to my knowledge, there is no feasible way of passing intermediate results between jobs in Travis.

**Comment by t-wissmann** [comment]
Ok Great! I think booting the VM is very acceptable!

**Pull request merged**
