### PR TITLE
Remove die() from utils

### PR DESCRIPTION
**Pull request by dnnr**
The current implementation of die() triggers a compiler warning
about the format string not being a literal.

Most of its points of usage are not really needed (malloc never fails[tm]),
or can be replaced with cerr/exit.

### CODE REVIEW

**Comment by dnnr** [comment]
Down the road, we should probably just throw exceptions and catch them in main().

But for now, I'd say this is fine.

**Comment by ypnos** [comment]
I only see two occasion where this method is used, one is some malloc bullshit we will get rid of anyway (and until then, malloc never fails[tm]). The other one can simply stderr and exit itself.

I suggest removal of die(). Additionally, I suggest to remove die() from ipc-utils as well.

**Comment by ypnos** [comment]
Note that fcb49946b0ba4c80b4f988fa9c70cc741074d2c6 introduced another point of usage.

**Comment by t-wissmann** [comment]
Right... right now, the "no display"-handling is twice anyway. Both in `XConnection` and in the `main()` function.

**Pull request merged**
