### PR TITLE
Try to fix flakyness in mouse tests

### PR DESCRIPTION
**Pull request by blarz**

### CODE REVIEW

**Comment by blarz** [comment]
Hrm, that does not seem to fix it.

**Comment by t-wissmann** [comment]
I think the "proper" way is what we are doing in `click` where we wait for the `ButtonPress` (resp. `ButtonRelease`) to be printed

**Comment by t-wissmann** [comment]
> I think the "proper" way is what we are doing in `click` where we wait for the `ButtonPress` (resp. `ButtonRelease`) to be printed

I've added a attempt as #881.

**Comment by blarz** [comment]
#881 should take care of that in a more elegant way

**Pull request closed without merging**
