### PR TITLE
New 'geometry' attribute for every monitor

### PR DESCRIPTION
**Pull request by t-wissmann**
The geometry (i.e. the rectangle) is the central property of a monitor,
so it deserves to be an attribute. This introduces 'rectangle' as a type
for attributes and adds some test cases for it.

### CODE REVIEW

**Comment by t-wissmann** [comment]
So far, we have called it `rectangle` instead `geometry` in the docs, but I think `geometry` is the more appropriate term (`rectangle` is only the type, and not was it does).

**Comment by blarz** [comment]
> So far, we have called it `rectangle` instead `geometry` in the docs, but I think `geometry` is the more appropriate term (`rectangle` is only the type, and not was it does).

Agreed!

**Review by blarz — DISMISSED** [review]
Looks good and works for me!

**Comment by blarz** [comment]
Seems like #1126 messed the build up for this PR

**Comment by t-wissmann** [comment]
> Seems like #1126 messed the build up for this PR

One include was missing, let's see what iwyu thinks about it :)

**Review by blarz — APPROVED** [review]

**Pull request merged**
