### PR TITLE
Synchronize mouse press/release with hlwm output

### PR DESCRIPTION
**Pull request by t-wissmann**
In the mouse fixture, wait for herbstluftwm to process the ButtonPress
and ButtonRelease events as we were doing it already in the Mouse.click()
method. This should fix the current flakyness of
test_drag_resize_floating_client

### CODE REVIEW

**Comment by t-wissmann** [comment]
An alternative to PR #877.

**Comment by blarz** [comment]
Hm still seems flaky

**Comment by t-wissmann** [comment]
> Hm still seems flaky

Hm maybe the python-xlib caches the geometry or didn't get the resize event ("configure notify") yet. Maybe a `x11.display.sync()` helps here. 

I've also added another parameter to run the test case multiple times (we did something similar in `test_drag_move`.)

**Comment by t-wissmann** [comment]
> > Hm still seems flaky
> 
> Hm maybe the python-xlib caches the geometry or didn't get the resize event ("configure notify") yet. Maybe a `x11.display.sync()` helps here.
> 
> I've also added another parameter to run the test case multiple times (we did something similar in `test_drag_move`.)

It still fails. I added another assertion, maybe this helps us to understand what's going on.

**Comment by t-wissmann** [comment]
Maybe we should still merge it, because I think the synchronization with the hlwm event queue should make things better anyway, even though it does not all race-conditions.

**Pull request merged**
