### PR TITLE
Enable clang-tidy check StackAddressEscape

### PR DESCRIPTION
**Pull request by dnnr**

### CODE REVIEW

**Comment by blarz** [comment]
That one is tricky complains about exit_on_error and another variable being passed around in a static struct.

**Comment by dnnr** [comment]
> That one is tricky complains about exit_on_error and another variable being passed around in a static struct.

Would making `exit_on_xerror` also `static` be a valid solution? I wonder why `long_options` is static in first place 🤔

**Comment by dnnr** [comment]
I think removing that `static` is the right way: #784

**Comment by t-wissmann** [comment]
Do I understand it correctly that these checks are enabled because they are deleted from the blacklist?

**Comment by dnnr** [comment]
> Do I understand it correctly that these checks are enabled because they are deleted from the blacklist?

Exactly!

**Pull request merged**
