### PR TITLE
CI: Remove some unused packages from Dockerfile

### PR DESCRIPTION
**Pull request by blarz**
Remove some unused packages and an outdated comment

### CODE REVIEW

**Comment by dnnr** [comment]
Nice! :rocket: Maybe adjust the title a bit before publishing.

**Comment by blarz** [comment]
> Nice! rocket Maybe adjust the title a bit before publishing.

Will do, thanks!

**Comment by blarz** [comment]
tox changes extracted into #924

**Comment by blarz** [comment]
Rebased and updated PR title

**Pull request merged**
