### PR TITLE
Make compatible with dmenu < 4.5

### PR DESCRIPTION
**Pull request by wilriker**
Also exit without creating a new rule if the user aborted dmenu selection

### CODE REVIEW

**Comment by t-wissmann** [comment]
What's the purpose of deleting the entire `dmenuPrintPath` function? Here with dmenu2 https://bitbucket.org/melek/dmenu2 I don't even have `dmenu_path` in my path. Or asking the other way around: what from the previous `dmenu_run_hlwm` has been incompatible to dmenu < 4.5?

**Comment by wilriker** [comment]
The problem with dmenu < 4.5 is that there is no `stest`. And as `dmenuPrintPath` was nearly exactly the content of dmenu 4.6's `dmenu_path` I thought it would make sense to direct the decision on how to compile the list over to dmenu.

Sadly I am stuck with CentOS 6 at work (as a friend of mine dubbed it: CenturyOldSoftware) I either have to use ancient versions of software from the (very restricted) repos. In that case it would be dmenu 4.1. Or I have to compile everything on my own (including hlwm) and I try to do this as few as possible (by the way, hlwm 0.7.0 is not being compiled by CentOS's ancient `gcc` - I don't remember the version by heart but it is one before they introduced lambdas) that's how I ran into this problem in the first place.

Nevertheless I did not know anything of dmenu2 and its lack of `dmenu_path`. I will submit a new patchset tomorrow that will look for what is available and takes a decision from that.

Best regards
Manuel

**Comment by t-wissmann** [comment]
All right, the new version seems to work for me. I have squashed your two commits into one, because the second commit re-introduces the dropped content of `dmenuPrintPath`. It's now in master.

Thanks for your contribution.

Regarding your `gcc` problem: from now on, you need a gcc/g++ or clang that supports `c++11`. Maybe you can statically compile link it on a newer OS and then use that binary on centos.

**Comment by wilriker** [comment]
Thanks for accepting!

> Regarding your gcc problem: from now on, you need a gcc/g++ or clang that supports c++11. Maybe you can statically compile link it on a newer OS and then use that binary on centos.

Yeah, I could try that. But right now I have the hopes that some changes in the companies structure will allow me to switch to Arch Linux next year - I'd prefer that by far! ;-) If that does not come true, I will try your proposal.

**Pull request closed without merging**
