### PR TITLE
 Cleanup interface of Input

### PR DESCRIPTION
**Pull request by ypnos**
Input is an ArgList that also stores the name of the command that
was called. It can only be constructed from a command name and (optionally) a
list of arguments to prevent wrong use.

All accessors from ArgList can be used. operator>> is overridden to
return the correct reference.

### CODE REVIEW

**Comment by t-wissmann** [comment]
Great! Thanks a lot. Looking over the changes, I think we can merge them once the CI finishes :-)

**Comment by ypnos** [comment]
The failure is some nasty crap, I didn't spot it because I had changed my debug flags, will fix it.

**Comment by t-wissmann** [comment]
Take your time!

**Comment by ypnos** [comment]
That's it from me for today :-)

**Comment by t-wissmann** [comment]
That was nasty indeed...

**Pull request merged**
