### PR TITLE
Add minimization keybinding to default autostart

### PR DESCRIPTION
**Pull request by blarz**
#1032 added this feature and had that nice keybind command in the commit message.
It fits perfectly into the default autostart.

### CODE REVIEW

**Review by t-wissmann — APPROVED** [review]
Thanks :) It's a nice follow up to #1104.

**Comment by t-wissmann** [comment]
Again, the github actions were not tirggered.

**Comment by tiosgz** [comment]
> Again, the github actions were not tirggered.

Isn’t it because `share/` is ignored?
https://github.com/herbstluftwm/herbstluftwm/blob/9421d93e7473448325b4b2ad70e6848f0c1cdfbf/.github/workflows/hlwm.yml#L10-L13

**Comment by t-wissmann** [comment]
> > Again, the github actions were not tirggered.
> 
> Isn’t it because `share/` is ignored?
> https://github.com/herbstluftwm/herbstluftwm/blob/9421d93e7473448325b4b2ad70e6848f0c1cdfbf/.github/workflows/hlwm.yml#L10-L13

Oh, good catch; thanks! So let's remove this ignore (the autostart is even tested by the test suite, so it should not be ignored).

**Comment by t-wissmann** [comment]
I've fixed it in bf6c1a9380eb41c09340d97e2ce54660098697f1 and pushed it to master directly.

**Pull request merged**
