### PR TITLE
Fix bash completion

### PR DESCRIPTION
**Pull request by tiosgz**
With the previous `herbstclient-completion` it did not really complete for me.

### CODE REVIEW

**Comment by blarz** [comment]
How this fix it? Was the filename incorrect?

**Comment by tiosgz** [comment]
Yeah (or at least on my system (Manjaro))

**Comment by tiosgz** [comment]
Oh! I should have tested if it works…

**Comment by t-wissmann** [comment]
I think the name in the git repository was correct: `share/herbstclient-completion` says what the file is good for (and `share/herbstclient-bash-completion` would be better, maybe even a separate directory for completions). However `share/herbstclient` is a misleading filename, in my opinion. So I think CMake should be configured in such a way that it changes the filename during installation (I don't know how to do this); maybe this is even obsolete, if the filepath is `shell-completions/herbstclient` (maybe even `shell-completions/herbstclient.bash`)

**Comment by tiosgz** [comment]
I'm not sure if I can do anything more than renaming it to `herbstclient.bash`, which seems to work (as you can see I'm even so naive that I thought just renaming the file is enough). Could you help me please?

**Comment by tiosgz** [comment]
OK, so I somehow managed to do it. However, I don't know how the file/folder system works, so I cannot move it into a separate directory.

I'm sorry for all those file renames, I guess I could have done it more systematically.

**Comment by t-wissmann** [comment]
Looks good, thanks! Don't worry about the renames. all commits of this PR are squashed into a single commit anyway.

**Comment by blarz** [comment]
This is merged now, but do we need to update the docs, now, too? faq.txt and INSTALL

**Comment by t-wissmann** [comment]
yes. faq.txt only mentioned the old install path. And I think INSTALL needs a reorganization anyway.

**Pull request merged**
