### PR TITLE
Apply rules to unmanaged popup windows

### PR DESCRIPTION
**Pull request by dnnr**

### CODE REVIEW

**Comment by t-wissmann** [comment]
I think the changes are fine. The only problem is (or is it a problem?) that a matching rule can switch the tag using `switchtag` although the unmanaged window is not on any tag at all.

**Comment by t-wissmann** [comment]
I think the changes are fine. The only problem is (or is it a problem?) that a matching rule can switch the tag using `switchtag` although the unmanaged window is not on any tag at all.

**Comment by dnnr** [comment]
Good point. Would this be solved by moving up the if-block where `force_unmanaged` is checked to right before the evaluation of `changes.monitor_name` (and ultimately `changes.switchtag`)? Seems to me that the order of these sections isn't vital, but I'm not sure.

**Comment by dnnr** [comment]
Is merged.

**Pull request closed without merging**
