### PR TITLE
Use bool literals instead of casting integers

### PR DESCRIPTION
**Pull request by dnnr**

### CODE REVIEW

**Comment by ypnos** [comment]
You are setting the initial value of several attributes to `true` while they were 0 before. In error?

**Comment by dnnr** [comment]
Oh boy, I've messed up the search&replace here, I'm terribly sorry. Fix is coming up!

**Comment by dnnr** [comment]
Should be correct now.

**Comment by t-wissmann** [comment]
Great, thanks!

**Pull request merged**
