### PR TITLE
Read monitor list from xrandr

### PR DESCRIPTION
**Pull request by t-wissmann**
Add monitor detection via xrandr. This also ads a cmake option to
disable this feature at compile time.

There is a separate xrandr event (see man 3 xrandr), which we don't ask
for at the moment, since listening to resolution changes (Root window
gets reconfigured) seems to be enough for the moment.

### CODE REVIEW

**Comment by dnnr** [comment]
What's the reason for making this compile-time configurable? I'd prefer if we didn't enter ifdef hell unless we really need to.

**Comment by t-wissmann** [comment]
it's another compile time dependency not everybody needs.

Related: somebody joined the irc and asked for xrandr support such that he can build hlwm without xinerama support to make the system xinerama-free.

And I can imagine that there are people that do it the other way round. I don't see the ifdef hell here.

**Comment by dnnr** [comment]
Any ifdef is ifdef hell, imho. :wink: But if there's demand for it, so be it. :+1: Is there something fishy about xinerama or xrandr that I'm not aware of? I'd just disable it if I didn't want to use it.

**Comment by t-wissmann** [comment]
I've made xrandr mandatory.

**Comment by dnnr** [comment]
Looks good to me, but I haven't tested it. Do you want me to?

**Comment by blarz** [comment]
Does the INSTALL file need an update, too? Or how specific is the list of dependencies?

**Comment by t-wissmann** [comment]
> Looks good to me, but I haven't tested it. Do you want me to?

I didn't know which corner cases to test, any ideas are welcome. Do you have any ideas how to test it in the testsuite?

> Does the INSTALL file need an update, too? Or how specific is the list of dependencies?

Right, we should update INSTALL as well!

**Comment by dnnr** [comment]
I got no idea... I assumed that manual testing is all we can do here.

**Comment by t-wissmann** [comment]
If you can test it manually, that would be great!

**Comment by t-wissmann** [comment]
It seems to work here, so let's merge it!

**Pull request merged**
