### PR TITLE
New command: export

### PR DESCRIPTION
**Pull request by t-wissmann**
Add a new command 'export' which is a convenience wrapper around 'setenv'.

### CODE REVIEW

**Comment by t-wissmann** [comment]
This command did not exist in master before, but I find it extremely useful  and reasonable and thus implemented it as a warm-up exercise to get used to the codebase and C++ again :-)

**Comment by dnnr** [comment]
Maybe I'm missing something, but how is different from setenv? Does it add anything, or is it just supposed to be a convenience *alias*?

**Comment by t-wissmann** [comment]
> Maybe I'm missing something, but how is it different from setenv? Does it add anything, or is it just supposed to be a convenience _alias_?

The difference is the `=` syntax:
```
herbstclient setenv FOO BAR
herbstclient export FOO=BAR
```
So it's the usual `export` syntax, just with `herbstclient` in front of it.

**Comment by dnnr** [comment]
I see. How about making it more explicit in the man page that one is really just an alias of the other (with a different separator), and then explain the actual functionality in just *one* of the commands, exclusively?

From a user's point of view, I think I'd be quite confused to see two options that seem identical yet are described differently. By each command "pretending" that the other one doesn't exist, it suggests some orthogonality that is not there.

**Comment by t-wissmann** [comment]
I thought I was doing this already. Now I've updated the description to make it really obvious that they're the same with different syntax.

**Comment by dnnr** [comment]
Alright, I think that's a bit better. 👍

**Pull request merged**
