### PR TITLE
Clarify method signature

### PR DESCRIPTION
**Pull request by ypnos**
Make clear that this does not alter the object

### CODE REVIEW

**Comment by ypnos** [comment]
Did we change to a PR-only model on winterbreeze? So I cannot push even small fixes like this because no travis. Is it the intention?

What is the workflow then, should I do every snippet in a PR or maybe have aggregated PRs that are developed alongside the feature/patch one is actually working on?

**Comment by ypnos** [comment]
Another issue I found in ArgList is the `operator[]` which ignores the internal shift. It is rarely used, to put it mildly. I am not sure but it looks like I will introduce the first usage right now (a command with variable number of arguments that should be processed one after another).
Please vote @dnnr, @t-wissmann 

1. Remove operator[], alternatives are to use begin()+end() or toVector()
2. Change behavior to start counting at `begin_`

**Comment by t-wissmann** [comment]
I've changed the branch properties that one can only merge PRs for which the checks pass. But I did not intend to force a PR-only model.

**Comment by t-wissmann** [comment]
I'm voting to remove `operator[]` because both its possible semantics (with or without shift) will cause confusion.

**Comment by ypnos** [comment]
Yes I think using the iterators instead works pretty well:

```
-    RectangleVec buf(argc);
-    for (int i = 0; i < argc; i++) {
-        buf[i] = Rectangle::fromStr(argv[i]);
-    }
+
+    RectangleVec buf;
+    for (auto &i : input) {
+        buf.push_back(Rectangle::fromStr(i));
+    }
```

**Comment by t-wissmann** [comment]
And I've changed your role, so maybe you're now allowed to push to winterbreeze directly. If this does not work either, I think we should drop the branch protection and just keep it as an informal rule to merge only PRs for which the checks pass.

**Comment by dnnr** [comment]
> So I cannot push even small fixes like this because no travis. Is it the intention?

The repo configuration change was my suggestion, as a mitigation for what happened in #164. But as Thorsten already said, we did not intend to prohibit direct pushes by project members.

However, I'd strongly recommend a workflow where every change goes through a PR with enforced automated checks. That said, I don't see any point in trying to *make* that happen for hlwm, so I'm just saying this as a suggestion to consider it.

> What is the workflow then, should I do every snippet in a PR or maybe have aggregated PRs that are developed alongside the feature/patch one is actually working on?

From my experience, I'd avoid aggregate PRs. Instead, one should keep CI build durations short in order to enable and encourage small-scale PRs.

**Comment by ypnos** [comment]
In general I am a huge fan of a stringent PR workflow due to the benefit of a four-eyes.

For *this* project I don't see a huge advantage of travis over running tox manually on my machine. Also *this* branch is still alpha quality and there are lots of small fixes that probably don't warrant the overhead.

So maybe we should agree to small fixes without PR to the winterbreeze branch at the discretion of the author, whereas somewhat bigger changes need a PR, and completely lock-down master?

At the same time, should we agree to a policy that one only accept other people's PRs, or introduce a LGTM system?

**Comment by dnnr** [comment]
> For _this_ project I don't see a huge advantage of travis over running tox manually on my machine. 

Well, the advantage I see is that a Travis build does a considerably more than I am usually doing locally, and this difference will probably increase over time (multiple compilers, ASAN, clang-tidy, coverage, etc.). From my personal experience, I actually enjoy the workflow of doing the quick superficial verification locally (like "does it build with *my* compiler?" and "does my IDE indicate warnings?") and then rely on the automated build to be much more thorough than that.

> So maybe we should agree to small fixes without PR to the winterbreeze branch at the discretion of the author, whereas somewhat bigger changes need a PR, and completely lock-down master?

Full ACK to that.

**Comment by ypnos** [comment]
Yes, Travis already showed its fruits since we have it here, and I look forward to enabling more features. When I currently push I don't go out for dinner before the tests are done :)

**Comment by ypnos** [comment]
Btw I will further improve on my last commit here.

**Pull request merged**
