### PR TITLE
Add 'parent_frame' entry for each client

### LINKED ISSUE #6: object tree: frame id (or object) as attribute of client
People sometimes ask how they get the correct frame ID for a rule.

Having a frame id (or with frame object, the object) as attribute/child of a client object might make this easier.

### PR DESCRIPTION
**Pull request by t-wissmann**
The 'parent_frame' child of a client provides the frame object that
holds the client.

This fixes #6.

### CODE REVIEW

**Comment by t-wissmann** [comment]
I'm not sure whether `frame` is a good name. Maybe something like `owning_frame` or `parent_frame` is better.

**Comment by blarz** [comment]
> I'm not sure whether `frame` is a good name. Maybe something like `owning_frame` or `parent_frame` is better.

parent_frame sounds nice IMHO

**Comment by t-wissmann** [comment]
Alright! I've renamed it to `parent_frame`.

**Review by blarz — APPROVED** [review]
Nice!

**Pull request merged**
