### PR TITLE
Move/reword keymask documentation for clarity

### PR DESCRIPTION
**Pull request by dnnr**

### CODE REVIEW

**Comment by dnnr** [comment]
By the way, I was a bit confused that this mechanism is only explained as a rule consequence. It's a standalone attribute that can be used without rules, isn't it?

**Comment by t-wissmann** [comment]
Yes. Actually it's the attribute that needs this documentation and the rule consequence just sets the attribute.

**Comment by dnnr** [comment]
I've shoehorned it into the attributes table now. Not sure how bad that is. See for yourself.

**Comment by t-wissmann** [comment]
It's fine, thanks!

**Pull request merged**
