### PR TITLE
React to focus stealing via XSetInputFocus

### PR DESCRIPTION
**Pull request by t-wissmann**
Usually, clients should request a focus change via an EWMH request,
which the WM can then respect or ignore. Some clients however just
change the input focus themselves (i.e. they change the window where
keyboard events are sent to), e.g. via XSetInputFocus().
Examples are `xdotool windowfocus` or `emacsclient -n $filename`.

The only way to handle these input focus changes is to update hlwm's
state to match the new focus. I am not entirely confident in the code
handling it, but it seems to update the clients.focus object accordingly
(see the new test case) and it does not trigger any endless loop (which
would happen without the XCheckMaskEvent()).

I assume that this fixes the issue #33.

### CODE REVIEW

**Review by blarz — APPROVED** [review]
Looks ok to me, let's see if it breaks anything :D

**Comment by t-wissmann** [comment]
I just had a horrible loop where the focus quickly togged between two windows (but I'm not able to reproduce it). I think this PR needs to be revised.

**Comment by blarz** [comment]
Oh noes, ok.. Revised or reverted? ;)

**Comment by t-wissmann** [comment]
Hopefully only 'revised', but maybe I should first check the icccm specification how focusing should work correctly.

**Pull request merged**
