### PR TITLE
Mark client urgent if focus stealing is not active

### PR DESCRIPTION
**Pull request by blarz**

### CODE REVIEW

**Comment by blarz** [comment]
Tried to address #914.

I think my assumptions on how this should work are wrong,
at least the test I wrote doesn't do what I expect it to do.

"activating" (NetActiveWindow) means also "starting" an application, right?
I thought creating a client on another tag should at least make it urgent.

Or did I understand the issue wrong?

**Comment by blarz** [comment]
Ok seems like starting the application does not trigger the activate thing, but for example opening a URL with from a terminal, which opens a new tab in firefox does.

So the change as such seems to work, I just don't know how to test it.

**Comment by t-wissmann** [comment]
> Ok seems like starting the application does not trigger the activate thing, but for example opening a URL from a terminal, which opens a new tab in firefox, does.
> 
> So the change as such seems to work, I just don't know how to test it.

I've changed it in your PR with the commit 9d10c70

**Comment by t-wissmann** [comment]
NetActiveWindow is the request to focus a particular window (e.g. task bars do this), but in fact any window can send such a request. The source-field usually tells the window manager whether the sender of the request considers itself as a 'taskbar/pager/...' or as an application window.

**Pull request merged**
