### PR TITLE
Use link time optimization in CI build

### PR DESCRIPTION
**Pull request by blarz**
Maybe finds some hidden problems and/or dead code.

### CODE REVIEW

**Comment by blarz** [comment]
Compilation seems to work. With gcc I see:
```../src/root.cpp: In member function ‘__ct_base ’:
../src/root.cpp:28:1: note: variable tracking size limit exceeded with ‘-fvar-tracking-assignments’, retrying without
sys	0m31.103s
   28 | Root::Root(Globals g, XConnection& xconnection, IpcServer& ipcServer)
      | ^
```

Not sure how critical that is...

**Comment by t-wissmann** [comment]
> Compilation seems to work. With gcc I see:
> 
> ```
> ../src/root.cpp:28:1: note: variable tracking size limit exceeded with ‘-fvar-tracking-assignments’, retrying without
> sys	0m31.103s
>    28 | Root::Root(Globals g, XConnection& xconnection, IpcServer& ipcServer)
>       | ^
> ```
> 
> Not sure how critical that is...

Hm not sure what `retrying without` means. Does it mean it compiles as if `-flto` was not passed?

**Comment by dnnr** [comment]
Unfortunately, this doesn't seem to provide any benefits in terms of improving code quality. Unless there's any other good reason for it, let's not do this.

**Comment by blarz** [comment]
Closing this.

**Pull request closed without merging**
