### PR TITLE
Test install target in CI run

### PR DESCRIPTION
**Pull request by blarz**
This should prevent issues like #1093

### CODE REVIEW

**Comment by blarz** [comment]
Should go green in the CI as soon as #1095 is submitted.

**Review by t-wissmann — APPROVED** [review]
Thanks! When it's merged, we can also move the `--install` to a separate step in the workflow

**Comment by blarz** [comment]
> Thanks! When it's merged, we can also move the `--install` to a separate step in the workflow

Makes sense.

I guess you need to merge this PR manually, as it modifies the workflow and mergify isn't allow to auto-submit this.

**Comment by t-wissmann** [comment]
> Thanks! When it's merged, we can also move the `--install` to a separate step in the workflow

It is a separate step in PR #1099.

**Pull request merged**
