### PR TITLE
Add basic python bindings

### PR DESCRIPTION
**Pull request by t-wissmann**
This initiates python bindings to herbstluftwm. The purpose of this is
to make it easier to write python scripts for hlwm. Moreover, as soon as
there are more useful functions in the bindings, we can also make use of
them in the test suite. Thus, we don't need a dedicated testsuite for
the bindings.

So far, the only functionality is call(), unchecked_call(), and
argument parsing.

### CODE REVIEW

**Comment by t-wissmann** [comment]
Also, I'm not sure what's the best name for the package. I went for `herbstluftwm` because it is more intuitive to use than `herbstclient`, even though the package only interacts with `herbstclient`.

**Comment by blarz** [comment]
> Also, I'm not sure what's the best name for the package. I went for `herbstluftwm` because it is more intuitive to use than `herbstclient`, even though the package only interacts with `herbstclient`.

I think that makes sense!

**Review by blarz — APPROVED** [review]
Let's get this thing rolling!

What about testing the bindings?
I didn't insist on having it in this PR, because it is implicitly tested by the testsuite.
But we should think about explicitly (unit) testing the bindings when more functionality is added.
What do you think?

**Comment by t-wissmann** [comment]
Thanks :) The new PR #1060 comes with test cases

**Pull request merged**
