### PR TITLE
Add tests fixture to log hooks

### PR DESCRIPTION
**Pull request by t-wissmann**
Add a hc_idle fixture that returns a list of hooks that have been
emitted so far.

### CODE REVIEW

**Comment by t-wissmann** [comment]
For some reason this fails in travis but works locally here. I can't explain why a race condition drops hooks...

**Comment by t-wissmann** [comment]
And now that I've  added debug output, the quantum decided to let the build pass...

**Comment by t-wissmann** [comment]
The build just failed for another PR because of this hook issue. I think we should disable the hook tests / revert the commit until we understand it fully..

**Comment by dnnr** [comment]
Agreed.

**Pull request merged**
