### PR TITLE
Do not set focused clients urgent

### PR DESCRIPTION
**Pull request by t-wissmann**

### CODE REVIEW

**Comment by t-wissmann** [comment]
Tests will follow

**Comment by tiosgz** [comment]
Yeah, this solves the main annoyance. Thanks!

**Comment by blarz** [comment]
> Tests will follow

In this PR or in a separate one?

**Comment by t-wissmann** [comment]
> > Tests will follow
> 
> In this PR or in a separate one?

As you wish. After @tiosgz's positive feedback, this small change in this PR might be save enough to be merged without a new testcase (for the moment)

**Comment by t-wissmann** [comment]
I've created a test case and uploaded it as a separate PR #941.

**Comment by blarz** [comment]
> I've created a test case and uploaded it as a separate PR #941.

Alrighty then!

**Pull request merged**
