### PR TITLE
Client alias 'longest-minimized' and 'last-minimized'

### PR DESCRIPTION
**Pull request by t-wissmann**
This adds client aliases for accessing the longest and the most recently
minimized client, and thus provides a native way to un-minimize clients
with key bindings (either in a lifo or fifo way). Thus, this also works
when minimizing clients via the panel and thus is more universal than
restricting to the unminimize.sh script (which was written for the lifo
unminimize).

With the new feature, we do not need the complicated binding for
unminimizing all clients anymore and we can move it to the faq (and
simplify it a bit).

This solves another feature request raised in the discussion of #1014.

### CODE REVIEW

**Comment by t-wissmann** [comment]
Should I remove the other un-minimize shortcut (Mod-Ctrl-m) that unminimizes all windows on a tag?

**Comment by blarz** [comment]
> Should I remove the other un-minimize shortcut (Mod-Ctrl-m) that unminimizes all windows on a tag?

I actually like that shortcut, at least the code that is behind it. But maybe we can remove/replace it as soon as #1262 is merged?

Also we could switch the new jumto last-minimized and the unminimize all shortcut?
Mod-Ctrl-Shift-m is quite a fingerbreaker (well, maybe not for emacs users :sweat_smile:)

**Comment by t-wissmann** [comment]
> > Should I remove the other un-minimize shortcut (Mod-Ctrl-m) that unminimizes all windows on a tag?
> 
> I actually like that shortcut, at least the code that is behind it. But maybe we can remove/replace it as soon as #1262 is merged?

I don't see the connection between #1262 and the keybinding for unminmizing all clients. #1262 manually implements `jumpto last-minimized`.

**Comment by blarz** [comment]
> > > Should I remove the other un-minimize shortcut (Mod-Ctrl-m) that unminimizes all windows on a tag?
> > 
> > 
> > I actually like that shortcut, at least the code that is behind it. But maybe we can remove/replace it as soon as #1262 is merged?
> 
> I don't see the connection between #1262 and the keybinding for unminmizing all clients. #1262 manually implements `jumpto last-minimized`.

Err, you're absolutely right, nevermind then!

**Comment by t-wissmann** [comment]
But we could bind `jumpto last-minimized` to `Mod-Ctrl-m` and move the `foreach` loop to an faq entry.

**Comment by blarz** [comment]
> But we could bind `jumpto last-minimized` to `Mod-Ctrl-m` and move the `foreach` loop to an faq entry.

I like it! That way the foreach is not lost and the FAQ is a good place to "store" it :)

**Comment by t-wissmann** [comment]
I've moved it.

**Review by blarz — APPROVED** [review]
Looks good to me, tested locally, test cases are also nice IMHO!

**Comment by t-wissmann** [comment]
Thanks!

**Pull request merged**
