### PR TITLE
Use correct comparison function in 'complete'

### PR DESCRIPTION
**Pull request by t-wissmann**
Thanks to the coverage reported, I've noticed that the function
parse_and_compare<unsigned long> was not used at all. The mistake was
introduced in 698dcd74ddbe96e96429c5ce874b2d099fd8c3cd.

It is hard to write a test case for it, but I've added some test case of
other yet non-covered parts of the error handling and completion of
'compare'.

### CODE REVIEW

**Review by blarz — APPROVED** [review]
Nice find! (The reviewer must have slept back then :sweat_smile:)

**Comment by t-wissmann** [comment]
> Nice find! (The reviewer must have slept back then )

I've introduced this mistake in 698dcd74ddbe96e96429c5ce874b2d099fd8c3cd long before the PR-based review process

**Comment by blarz** [comment]
> > Nice find! (The reviewer must have slept back then )
> 
> I've introduced this mistake in [698dcd7](https://github.com/herbstluftwm/herbstluftwm/commit/698dcd74ddbe96e96429c5ce874b2d099fd8c3cd) long before the PR-based review process

I see! I thought I missed that one maybe :D

**Comment by t-wissmann** [comment]
It seems it does not only improve coverage but also uncovers more error messages on stdout.

**Review by blarz — APPROVED** [review]

**Pull request merged**
