### PR TITLE
'resize' command: make delta parameter optional

### PR DESCRIPTION
**Pull request by t-wissmann**
Recently the 'resize' command became also functional in the floating
mode, where the 'FRACTIONDELTA' parameter is not used at all. In the
tiling mode, the parameter is most likely '0.02' for most people. Hence,
it makes sense to make the parameter optional, so one can now run e.g.

   herbstclient resize up

to make the focused client (or frame) grow into the upward direction.

### CODE REVIEW

**Comment by blarz** [comment]
In the default autostart, resizestep is 0.05 FWIW

**Comment by t-wissmann** [comment]
Oh, right. Hm any opinions on that?
My impression is that `0.05` is quite (too?) coarse..

**Comment by blarz** [comment]
> Oh, right. Hm any opinions on that?
> My impression is that `0.05` is quite (too?) coarse..

We could change the default.
It is only a one line change to get the old delta back if users want it more coarse.

**Comment by t-wissmann** [comment]
> > Oh, right. Hm any opinions on that?
> > My impression is that `0.05` is quite (too?) coarse..
> 
> We could change the default.
> It is only a one line change to get the old delta back if users want it more coarse.

I've updated it as a separate PR in #842.

**Pull request merged**
