### PR TITLE
Remove Travis everywhere

### PR DESCRIPTION
**Pull request by blarz**
Bye bye...

### CODE REVIEW

**Review by t-wissmann — APPROVED** [review]
:-) We can add a gh action badge at some point

**Comment by blarz** [comment]
The GH actions are run on my fork, that is why "checks haven't completed" in this PR and mergify doesn't merge it automatically.

**Comment by t-wissmann** [comment]
> The GH actions are run on my fork, that is why "checks haven't completed" in this PR and mergify doesn't merge it automatically.

Ah, I see. Maybe #1070 fixes it.

**Comment by blarz** [comment]
> > The GH actions are run on my fork, that is why "checks haven't completed" in this PR and mergify doesn't merge it automatically.
> 
> Ah, I see. Maybe #1070 fixes it.

Aweseome, thank you!

But it also seems like it is possible to have flaky tests with GHA ;)

**Pull request merged**
