### PR TITLE
Fix typo of the word 'writable'

### PR DESCRIPTION
**Pull request by t-wissmann**
Since `writable` is the more standard spelling (and I'm unintentionally writing
it anyway) change everything to `writable`:

    sed -i 's,\(writ\)e\(able\),\1\2,ig' `git ls-files|grep -v ^ci/` 

(the `grep -v` is only to ignore the `ci` directory, which contains a symbolic
link which would get destroyed by `sed -i`). Grep proves that we caught all
occurrences:

    grep -i writeable `git ls-files`

### CODE REVIEW

**Comment by blarz** [comment]
As far as I can see both forms are fine (according to various dictionaries).
My browser's spell checker seems to prefer writable over writeable :D

**Comment by t-wissmann** [comment]
Oh indeed... it seems like `writeable` is the alternative spelling of `writable`.

**Comment by t-wissmann** [comment]
We've always used `writeable` so far (in the man page and the output of the `attr` command). Should we change it to `writable`? I think we should make it consistent and we should make a decision before #1082 is merged :)

**Comment by tiosgz** [comment]
If I may help you decide…
* you always use *-ize* (US)
* in programming are, AFAIK, preferred US forms & words
* according to [Wiki](https://en.wikipedia.org/wiki/American_and_British_English_spelling_differences#Dropped_%22e%22), *writeable* is rather UK English (& now that I’m writing it, it seems that my browser’s spell checker doesn’t know it even though I do have BrE dictionary)

**Comment by t-wissmann** [comment]
Right, so I should actually make the inverse pull request where  I replace `writeable` by `writable`.

**Review by blarz — APPROVED** [review]
writable seems to make the most sense

**Pull request merged**
