### PR TITLE
Add minimization keybinding to default autostart

### PR DESCRIPTION
**Pull request by blarz**
#1032 added this feature and had that nice keybind command in the commit message.
It fits perfectly into the default autostart.

### CODE REVIEW

**Comment by tiosgz** [comment]
Guess you’ll have to change your commit details or hlwm will get a new contributor ;)

**Comment by blarz** [comment]
> Guess you’ll have to change your commit details or hlwm will get a new contributor ;)
> 
> // I see it’s okay in the resulting commit in #1105

D'oh, I did the commit on my work laptop.. Thanks for noticing, I'll fix it.

**Comment by t-wissmann** [comment]
mergify does a squash commit and I'd assume the user opening the PR will become the commit's author. I think it's a good idea to have it as a default binding. I personally have `Mod-m` on maximize.sh and `Mod-Shift-m` on the minimize command, because I use maximization more often. But we can also add it like this and swap the keybindings later.

**Comment by t-wissmann** [comment]
For some reason, the github CI does not show up for this pr. Maybe it returns when we press 'update branch' (after there is something new in master)

**Comment by blarz** [comment]
I will open a new PR with my regular account and will change to Mod-Shfit-m

**Pull request closed without merging**
