### PR TITLE
Turn HSRule struct into a class

### PR DESCRIPTION
**Pull request by dnnr**

### CODE REVIEW

**Comment by dnnr** [comment]
This PR includes #195 and needs to be updated after that once was merged.

**Comment by t-wissmann** [comment]
> This PR includes #195 and needs to be updated after that once was merged.

Does it really? If this contains #195, why do we have conflicts then?

**Comment by t-wissmann** [comment]
Can you take a look at the conflicts?

Thanks for cleaning this file up :-)

**Comment by dnnr** [comment]
I probably caused those conflicts by rebasing one of the branches. I've fixed them, but had to include #199 into this PR, so that one should go first (but it should anyway). I'll merge again afterwards.

**Pull request merged**
