### PR TITLE
Add "const" to rule applier methods

### PR DESCRIPTION
**Pull request by dnnr**

### CODE REVIEW

**Comment by dnnr** [comment]
This includes changes from #260 

We might not want to merge this (but we could), so this is primarily meant as a basis for discussion. See the TODO in HSConsequence declaration.

Should I resolve the TODO by giving the `applyEwmh…` methods the same treatment I gave `applyPseudotile` in #260? I wasn't entirely sure here...

**Comment by t-wissmann** [comment]
If we do so, then (except for `hook=`) all applier methods will look the same, namely:
```
HSConsequence::applyFoo(....) {
   clientchanges->foo = string_to_bool/int/...(value);
}
```
I don't think this is a bad thing but simply room for further optimizations (that are not urgent).

**Comment by dnnr** [comment]
Alright! Then let's just keep this PR open until it's done.

**Comment by dnnr** [comment]
Includes #265 now, too

**Comment by dnnr** [comment]
Should be good to go now (finally...)

**Pull request merged**
