### PR TITLE
Let objects have documentation

### PR DESCRIPTION
**Pull request by t-wissmann**
This makes Object inherit from HasDocumentation and parses the
respective calls to setDoc() into the json document. The attr command
now prints this object documentation, and this allows us to add test
cases that it matches the doc in the json file.

Note that the object documentation is something different than the
documentation on these "child entries" because e.g. the documentation on
clients.focus is "the focused client" whereas the documentation on
Client is that it represents "a managed window".

### CODE REVIEW

**Comment by blarz** [comment]
Shouldn't this trigger the json diff posting by the bot?

**Comment by t-wissmann** [comment]
> Shouldn't this trigger the json diff posting by the bot?

I'm running `ci/diff-json-doc.py` locally because it's not yet part of github actions.

**Comment by blarz** [comment]
> > Shouldn't this trigger the json diff posting by the bot?
> 
> I'm running `ci/diff-json-doc.py` locally because it's not yet part of github actions.

I see, that makes sense. Thanks for the diff!

**Review by blarz — APPROVED** [review]

**Comment by t-wissmann** [comment]
One line had trailing whitespaces after I did the merge commit in the github web interface. I've fixed it but this removed the approval.

**Review by blarz — APPROVED** [review]

**Pull request merged**
