### PR TITLE
Enable some clang-analyzer-unix checks

### PR DESCRIPTION
**Pull request by dnnr**
These checks used to fail when initially adding clang-tidy to the pipeline.
The underlying issues have probably been fixed in the mean-time.

### CODE REVIEW

**Comment by blarz** [comment]
Explain?

**Comment by dnnr** [comment]
> Explain?

I was confused, too. See description, now

**Comment by dnnr** [comment]
Added another check...

**Comment by blarz** [comment]
I think the malloc one was in #767 maybe?

**Comment by dnnr** [comment]
> I think the malloc one was in #767 maybe?

It was indeed!

**Comment by blarz** [comment]
Does simply removing the checks from the '-' list also add them automatically?
Or do we need to add them explicitly?

**Comment by blarz** [comment]
> Does simply removing the checks from the '-' list also add them automatically?
> Or do we need to add them explicitly?

Ah just looked at the list of enabled checks in the build output, the checks are enabled.

**Comment by dnnr** [comment]
> Does simply removing the checks from the '-' list also add them automatically?
> Or do we need to add them explicitly?

This is not really obvious. Technically, I'm not enabling those checks, but I'm allowing them to run if they are in the default set of checks (which they were when introducing clang-tidy).

**Pull request merged**
